# minified version of circleci; should be removed once fully switched over
version: 2.1

executors:
  circle-jdk-executor:
    working_directory: ~/rewrite-gradle-plugin
    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
    docker:
      - image: cimg/openjdk:11.0
  machine-executor:
    working_directory: ~/rewrite-gradle-plugin
    machine:
      image: ubuntu-1604:201903-01

commands:
  gradlew-build:
    description: "Run a Gradle build using the wrapper"
    parameters:
      command:
        type: string
        default: "check test"
    steps:
      - checkout
      - run:
          name: run gradle command
          command: ./gradlew << parameters.command >>

jobs:
  build:
    executor: circle-jdk-executor
    steps:
      - gradlew-build

workflows:
  version: 2
  build_prs_deploy_snapshots:
    jobs:
      - build
