{
 "title": "Rewrite Checkstyle 2",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Changes Recommended", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Maximum Recommended Source File Changes by Project",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rewrite_refactor_plan_seconds_count{outcome=\"Changed\"}) by (project_name, project_root_project_name)",
     "legendFormat": "{{project_root_project_name}}:{{project_name}}"
    }
   ]
  },
  {
   "title": "Max Source Files Changed by Check",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rewrite_refactor_plan_changes_total) by (visitor)",
     "legendFormat": "{{visitor}}"
    }
   ]
  },
  { "title": "Time Spent", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Top 3 Most Time Spent in Refactoring by Project",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(3, max(rewrite_refactor_plan_seconds_max) by (project_name, project_root_project_name))",
     "legendFormat": "{{project_root_project_name}}:{{project_name}}"
    }
   ]
  },
  {
   "title": "Top 3 Most Time Spent Running a Check on an Individual Source File",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(3, max(rewrite_refactor_visit_seconds_max) by (visitor))",
     "legendFormat": "{{visitor}}"
    }
   ]
  },
  {
   "title": "99th Percentile Time Spent in Parsing Phases",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rewrite_parse_seconds_bucket[2m])) by (le, step))",
     "legendFormat": "{{step}}"
    }
   ]
  }
 ]
}